---
title: Konekti
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    author: Jeff Loughridge
    image: postimage
description: 
url: https://konekti.us
baseurl: 
twitter: konekti_systems
facebook: 
email: info@konekti.us
environment: production
disqus:
  shortname: konekti-us
markdown: kramdown
theme: minima
highlighter: rouge
data-tweet-limit: 2
paginate: 5
paginate_path: "/blog/page:num/"
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-paginate
exclude:
- Gemfile
- Gemfile.lock
excerpt_separator: "<!--excerpt-->"
