---
title: Konekti
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    author: Jeff Loughridge
    image: postimage
    parent: blog
description: "Konekti Systems helps clients develop and implement cloud and hybrid networks, enabling them to migrate to and between public clouds painlessly."
url: https://konekti.us
baseurl: ''
twitter: konekti_systems
data-tweet-limit: 2
facebook: 
email: info@konekti.us
environment: production
disqus:
  shortname: konekti-us
markdown: kramdown
highlighter: rouge
paginate: 5
paginate_path: "/blog/:num/"
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-paginate
exclude:
- Gemfile
- Gemfile.lock
include:
  - _pages
excerpt_separator: "<!--excerpt-->"

designer:
  name: Weru
  url: https://neuralvibes.com/author/
sass:
  style: compressed
formcarry: BJEUqzP-7
mailchimp:
  show: true
  url: 'https://konekti.us19.list-manage.com/subscribe/post?u=91ca13ebadc8d8afad64c838a&amp;id=c461d318b7'
  hidden: 'b_91ca13ebadc8d8afad64c838a_c461d318b7'
