Description:
    This template deploys a VPC with two Availability Zones, each with
    one subnet. It also deploys an Internet Gateway and a Route Table.

Parameters:

    EnvironmentName:
        Description:
            Please enter a name for this VPC
        Type: String
        Default: Konekti-prod

    VpcCIDR:
        Description:
            Please enter the IP range in CIDR notation for this VPC
        Type: String
        Default: 172.25.0.0/16

    Subnet1CIDR:
        Description:
            Please enter the IP range in CIDR notation for the
            subnet in the first Availability Zone
        Type: String
        Default: 172.25.30.0/24

    Subnet2CIDR:
        Description:
            Please enter the IP range (CIDR notation) for the
            subnet in the second Availability Zone
        Type: String
        Default: 172.25.32.0/24

Resources:

    VPC:
        Type: AWS::EC2::VPC
        Properties:
            CidrBlock: !Ref VpcCIDR
            Tags:
                - Key: Name
                  Value: !Ref EnvironmentName

    InternetGateway:
        Type: AWS::EC2::InternetGateway
        Properties:
            Tags:
                - Key: Name
                  Value: !Ref EnvironmentName

    InternetGatewayAttachment:
        Type: AWS::EC2::VPCGatewayAttachment
        Properties:
            InternetGatewayId: !Ref InternetGateway
            VpcId: !Ref VPC

    Subnet1:
        Type: AWS::EC2::Subnet
        Properties:
            VpcId: !Ref VPC
            AvailabilityZone: !Select [ 0, !GetAZs '' ]
            CidrBlock: !Ref Subnet1CIDR
            MapPublicIpOnLaunch: false
            Tags:
                - Key: Name
                  Value: !Sub ${EnvironmentName} AZ1

    Subnet2:
        Type: AWS::EC2::Subnet
        Properties:
            VpcId: !Ref VPC
            AvailabilityZone: !Select [ 1, !GetAZs '' ]
            CidrBlock: !Ref Subnet2CIDR
            MapPublicIpOnLaunch: false
            Tags:
                - Key: Name
                  Value: !Sub ${EnvironmentName} AZ2

    RouteTable:
        Type: AWS::EC2::RouteTable
        Properties:
            VpcId: !Ref VPC
            Tags:
                - Key: Name
                  Value: !Sub ${EnvironmentName}

    DefaultRoute:
        Type: AWS::EC2::Route
        DependsOn: InternetGatewayAttachment
        Properties:
            RouteTableId: !Ref RouteTable
            DestinationCidrBlock: 0.0.0.0/0
            GatewayId: !Ref InternetGateway

    Subnet1RouteTableAssociation:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
            RouteTableId: !Ref RouteTable
            SubnetId: !Ref Subnet1

    Subnet2RouteTableAssociation:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
            RouteTableId: !Ref RouteTable
            SubnetId: !Ref Subnet2

Outputs:

    VPC:
        Description: A reference to the created VPC
        Value: !Ref VPC

    Subnets:
        Description: A list of the  subnets
        Value: !Join [ ",", [ !Ref Subnet1, !Ref Subnet2 ]]

    Subnet1:
        Description: A reference to the  subnet in the 1st Availability Zone
        Value: !Ref Subnet1

    Subnet2:
        Description: A reference to the  subnet in the 2nd Availability Zone
        Value: !Ref Subnet2

    SecurityGroup:
        Description: VPC Default Security Group
        Value: !GetAtt VPC.DefaultSecurityGroup

